/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { SkillMeatClient } from './SkillMeatClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AddArtifactsRequest } from './models/AddArtifactsRequest';
export type { AddGroupArtifactsRequest } from './models/AddGroupArtifactsRequest';
export type { AddMemoryToModuleRequest } from './models/AddMemoryToModuleRequest';
export type { AllServersHealthResponse } from './models/AllServersHealthResponse';
export type { AnalyticsSummaryResponse } from './models/AnalyticsSummaryResponse';
export type { ArtifactCollectionInfo } from './models/ArtifactCollectionInfo';
export type { ArtifactCreateRequest } from './models/ArtifactCreateRequest';
export type { ArtifactCreateResponse } from './models/ArtifactCreateResponse';
export type { ArtifactDeployRequest } from './models/ArtifactDeployRequest';
export type { ArtifactDeployResponse } from './models/ArtifactDeployResponse';
export type { ArtifactDiffResponse } from './models/ArtifactDiffResponse';
export type { ArtifactGroupMembership } from './models/ArtifactGroupMembership';
export type { ArtifactListResponse } from './models/ArtifactListResponse';
export type { ArtifactMetadataResponse } from './models/ArtifactMetadataResponse';
export type { ArtifactParameters } from './models/ArtifactParameters';
export type { ArtifactPopularity } from './models/ArtifactPopularity';
export type { ArtifactPositionUpdate } from './models/ArtifactPositionUpdate';
export type { ArtifactResponse } from './models/ArtifactResponse';
export type { ArtifactScoreResponse } from './models/ArtifactScoreResponse';
export type { ArtifactSourceType } from './models/ArtifactSourceType';
export type { ArtifactSyncRequest } from './models/ArtifactSyncRequest';
export type { ArtifactSyncResponse } from './models/ArtifactSyncResponse';
export type { ArtifactTagsUpdate } from './models/ArtifactTagsUpdate';
export type { ArtifactUpdateMetadataRequest } from './models/ArtifactUpdateMetadataRequest';
export type { ArtifactUpdateRequest } from './models/ArtifactUpdateRequest';
export type { ArtifactUpstreamDiffResponse } from './models/ArtifactUpstreamDiffResponse';
export type { ArtifactUpstreamInfo } from './models/ArtifactUpstreamInfo';
export type { ArtifactUpstreamResponse } from './models/ArtifactUpstreamResponse';
export type { ArtifactVersionInfo } from './models/ArtifactVersionInfo';
export type { AutoTagRefreshResponse } from './models/AutoTagRefreshResponse';
export type { AutoTagSegment } from './models/AutoTagSegment';
export type { AutoTagsResponse } from './models/AutoTagsResponse';
export type { Body_import_bundle_api_v1_bundles_import_post } from './models/Body_import_bundle_api_v1_bundles_import_post';
export type { Body_preview_bundle_api_v1_bundles_preview_post } from './models/Body_preview_bundle_api_v1_bundles_preview_post';
export type { Body_undeploy_artifact_api_v1_artifacts__artifact_id__undeploy_post } from './models/Body_undeploy_artifact_api_v1_artifacts__artifact_id__undeploy_post';
export type { Body_validate_bundle_api_v1_bundles_validate_post } from './models/Body_validate_bundle_api_v1_bundles_validate_post';
export type { BrokerInfo } from './models/BrokerInfo';
export type { BrokerListResponse } from './models/BrokerListResponse';
export type { BulkActionResponse } from './models/BulkActionResponse';
export type { BulkAutoTagRefreshItemResult } from './models/BulkAutoTagRefreshItemResult';
export type { BulkAutoTagRefreshRequest } from './models/BulkAutoTagRefreshRequest';
export type { BulkAutoTagRefreshResponse } from './models/BulkAutoTagRefreshResponse';
export type { BulkDeprecateRequest } from './models/BulkDeprecateRequest';
export type { BulkImportArtifact } from './models/BulkImportArtifact';
export type { BulkImportRequest } from './models/BulkImportRequest';
export type { BulkImportResult } from './models/BulkImportResult';
export type { BulkPromoteRequest } from './models/BulkPromoteRequest';
export type { BulkSyncItemResult } from './models/BulkSyncItemResult';
export type { BulkSyncRequest } from './models/BulkSyncRequest';
export type { BulkSyncResponse } from './models/BulkSyncResponse';
export type { BundleAnalyticsResponse } from './models/BundleAnalyticsResponse';
export type { BundleArtifactSummary } from './models/BundleArtifactSummary';
export type { BundleDeleteResponse } from './models/BundleDeleteResponse';
export type { BundleDetailResponse } from './models/BundleDetailResponse';
export type { BundleExportMetadata } from './models/BundleExportMetadata';
export type { BundleExportOptions } from './models/BundleExportOptions';
export type { BundleExportRequest } from './models/BundleExportRequest';
export type { BundleExportResponse } from './models/BundleExportResponse';
export type { BundleImportResponse } from './models/BundleImportResponse';
export type { BundleListItem } from './models/BundleListItem';
export type { BundleListResponse } from './models/BundleListResponse';
export type { BundleMetadataResponse } from './models/BundleMetadataResponse';
export type { BundlePreviewCategorization } from './models/BundlePreviewCategorization';
export type { BundlePreviewResponse } from './models/BundlePreviewResponse';
export type { BundleValidationResponse } from './models/BundleValidationResponse';
export type { CachedArtifactResponse } from './models/CachedArtifactResponse';
export type { CachedArtifactsListResponse } from './models/CachedArtifactsListResponse';
export type { CachedProjectResponse } from './models/CachedProjectResponse';
export type { CachedProjectsListResponse } from './models/CachedProjectsListResponse';
export type { CacheInfo } from './models/CacheInfo';
export type { CacheInvalidateRequest } from './models/CacheInvalidateRequest';
export type { CacheInvalidateResponse } from './models/CacheInvalidateResponse';
export type { CacheRefreshRequest } from './models/CacheRefreshRequest';
export type { CacheRefreshResponse } from './models/CacheRefreshResponse';
export type { CacheStatusResponse } from './models/CacheStatusResponse';
export type { CatalogEntryResponse } from './models/CatalogEntryResponse';
export type { CatalogListResponse } from './models/CatalogListResponse';
export type { CatalogSearchResponse } from './models/CatalogSearchResponse';
export type { CatalogSearchResult } from './models/CatalogSearchResult';
export type { CollectionListResponse } from './models/CollectionListResponse';
export type { CollectionMatch } from './models/CollectionMatch';
export type { CollectionResponse } from './models/CollectionResponse';
export type { ConfirmDuplicatesRequest } from './models/ConfirmDuplicatesRequest';
export type { ConfirmDuplicatesResponse } from './models/ConfirmDuplicatesResponse';
export type { ConfirmDuplicatesStatus } from './models/ConfirmDuplicatesStatus';
export type { ConflictInfo } from './models/ConflictInfo';
export type { ConflictMetadataResponse } from './models/ConflictMetadataResponse';
export type { ConflictResolveRequest } from './models/ConflictResolveRequest';
export type { ConflictResolveResponse } from './models/ConflictResolveResponse';
export type { ContextEntityCreateRequest } from './models/ContextEntityCreateRequest';
export type { ContextEntityInfo } from './models/ContextEntityInfo';
export type { ContextEntityListResponse } from './models/ContextEntityListResponse';
export type { ContextEntityResponse } from './models/ContextEntityResponse';
export type { ContextEntityType } from './models/ContextEntityType';
export type { ContextEntityUpdateRequest } from './models/ContextEntityUpdateRequest';
export type { ContextMapResponse } from './models/ContextMapResponse';
export type { ContextModuleCreateRequest } from './models/ContextModuleCreateRequest';
export type { ContextModuleListResponse } from './models/ContextModuleListResponse';
export type { ContextModuleResponse } from './models/ContextModuleResponse';
export type { ContextModuleUpdateRequest } from './models/ContextModuleUpdateRequest';
export type { ContextPackGenerateRequest } from './models/ContextPackGenerateRequest';
export type { ContextPackGenerateResponse } from './models/ContextPackGenerateResponse';
export type { ContextPackPreviewRequest } from './models/ContextPackPreviewRequest';
export type { ContextPackPreviewResponse } from './models/ContextPackPreviewResponse';
export type { CopyGroupRequest } from './models/CopyGroupRequest';
export type { CreateLinkedArtifactRequest } from './models/CreateLinkedArtifactRequest';
export type { CreateSourceRequest } from './models/CreateSourceRequest';
export type { DeployedArtifact } from './models/DeployedArtifact';
export type { DeploymentInfo } from './models/DeploymentInfo';
export type { DeploymentListResponse } from './models/DeploymentListResponse';
export type { DeploymentModificationStatus } from './models/DeploymentModificationStatus';
export type { DeploymentRequest } from './models/DeploymentRequest';
export type { DeploymentStatistics } from './models/DeploymentStatistics';
export type { DeploymentStatusResponse } from './models/DeploymentStatusResponse';
export type { DeploymentSummary } from './models/DeploymentSummary';
export type { DeployRequest } from './models/DeployRequest';
export type { DeployTemplateRequest } from './models/DeployTemplateRequest';
export type { DeployTemplateResponse } from './models/DeployTemplateResponse';
export type { DeprecateRequest } from './models/DeprecateRequest';
export type { DetailedHealthStatus } from './models/DetailedHealthStatus';
export type { DetectedArtifact } from './models/DetectedArtifact';
export type { DetectionPatternsResponse } from './models/DetectionPatternsResponse';
export type { DiscoveredArtifact } from './models/DiscoveredArtifact';
export type { DiscoveryRequest } from './models/DiscoveryRequest';
export type { DiscoveryResult } from './models/DiscoveryResult';
export type { DriftDetectionResponse } from './models/DriftDetectionResponse';
export type { DriftSummaryResponse } from './models/DriftSummaryResponse';
export type { DuplicateDecisionAction } from './models/DuplicateDecisionAction';
export type { DuplicateMatch } from './models/DuplicateMatch';
export type { ErrorReasonCode } from './models/ErrorReasonCode';
export type { ErrorResponse } from './models/ErrorResponse';
export type { ExcludeArtifactRequest } from './models/ExcludeArtifactRequest';
export type { ExtractedSegmentResponse } from './models/ExtractedSegmentResponse';
export type { FileDiff } from './models/FileDiff';
export type { FileListResponse } from './models/FileListResponse';
export type { FileNode } from './models/FileNode';
export type { FileTreeEntry } from './models/FileTreeEntry';
export type { FileTreeResponse } from './models/FileTreeResponse';
export type { FileUpdateRequest } from './models/FileUpdateRequest';
export type { GitHubMetadata } from './models/GitHubMetadata';
export type { GitHubTokenRequest } from './models/GitHubTokenRequest';
export type { GitHubTokenStatusResponse } from './models/GitHubTokenStatusResponse';
export type { GitHubTokenValidationResponse } from './models/GitHubTokenValidationResponse';
export type { GroupArtifactResponse } from './models/GroupArtifactResponse';
export type { GroupCreateRequest } from './models/GroupCreateRequest';
export type { GroupListResponse } from './models/GroupListResponse';
export type { GroupPositionUpdate } from './models/GroupPositionUpdate';
export type { GroupReorderRequest } from './models/GroupReorderRequest';
export type { GroupResponse } from './models/GroupResponse';
export type { GroupSummary } from './models/GroupSummary';
export type { GroupUpdateRequest } from './models/GroupUpdateRequest';
export type { GroupWithArtifactsResponse } from './models/GroupWithArtifactsResponse';
export type { HealthCheckResponse } from './models/HealthCheckResponse';
export type { HealthStatus } from './models/HealthStatus';
export type { HTTPValidationError } from './models/HTTPValidationError';
export type { ImportedArtifactResponse } from './models/ImportedArtifactResponse';
export type { ImportRequest } from './models/ImportRequest';
export type { ImportResult } from './models/ImportResult';
export type { ImportResultDTO } from './models/ImportResultDTO';
export type { ImportStatus } from './models/ImportStatus';
export type { IndexingModeResponse } from './models/IndexingModeResponse';
export type { InferUrlRequest } from './models/InferUrlRequest';
export type { InferUrlResponse } from './models/InferUrlResponse';
export type { InstallRequest } from './models/InstallRequest';
export type { InstallResponse } from './models/InstallResponse';
export type { LinkedArtifactReferenceSchema } from './models/LinkedArtifactReferenceSchema';
export type { ListingDetailResponse } from './models/ListingDetailResponse';
export type { ListingResponse } from './models/ListingResponse';
export type { ListingsPageResponse } from './models/ListingsPageResponse';
export type { MarketplaceEntryResponse } from './models/MarketplaceEntryResponse';
export type { MarketplaceListResponse } from './models/MarketplaceListResponse';
export type { MatchedArtifact } from './models/MatchedArtifact';
export type { MatchResponse } from './models/MatchResponse';
export type { MCPServerCreateRequest } from './models/MCPServerCreateRequest';
export type { MCPServerListResponse } from './models/MCPServerListResponse';
export type { MCPServerResponse } from './models/MCPServerResponse';
export type { MCPServerUpdateRequest } from './models/MCPServerUpdateRequest';
export type { MemoryItemCreateRequest } from './models/MemoryItemCreateRequest';
export type { MemoryItemListResponse } from './models/MemoryItemListResponse';
export type { MemoryItemResponse } from './models/MemoryItemResponse';
export type { MemoryItemUpdateRequest } from './models/MemoryItemUpdateRequest';
export type { MemoryStatus } from './models/MemoryStatus';
export type { MemoryType } from './models/MemoryType';
export type { MergeAnalyzeRequest } from './models/MergeAnalyzeRequest';
export type { MergeDeployDetails } from './models/MergeDeployDetails';
export type { MergeExecuteRequest } from './models/MergeExecuteRequest';
export type { MergeExecuteResponse } from './models/MergeExecuteResponse';
export type { MergeFileAction } from './models/MergeFileAction';
export type { MergePreviewRequest } from './models/MergePreviewRequest';
export type { MergePreviewResponse } from './models/MergePreviewResponse';
export type { MergeRequest } from './models/MergeRequest';
export type { MergeResponse } from './models/MergeResponse';
export type { MergeSafetyResponse } from './models/MergeSafetyResponse';
export type { MessageResponse } from './models/MessageResponse';
export type { MetadataFetchResponse } from './models/MetadataFetchResponse';
export type { ModificationCheckResponse } from './models/ModificationCheckResponse';
export type { ModifiedArtifactInfo } from './models/ModifiedArtifactInfo';
export type { ModifiedArtifactsResponse } from './models/ModifiedArtifactsResponse';
export type { PageInfo } from './models/PageInfo';
export type { ParameterUpdateRequest } from './models/ParameterUpdateRequest';
export type { ParameterUpdateResponse } from './models/ParameterUpdateResponse';
export type { PathSegmentsResponse } from './models/PathSegmentsResponse';
export type { PreviewArtifact } from './models/PreviewArtifact';
export type { ProjectCreateRequest } from './models/ProjectCreateRequest';
export type { ProjectCreateResponse } from './models/ProjectCreateResponse';
export type { ProjectDeleteResponse } from './models/ProjectDeleteResponse';
export type { ProjectDeploymentInfo } from './models/ProjectDeploymentInfo';
export type { ProjectDeploymentRemovalResponse } from './models/ProjectDeploymentRemovalResponse';
export type { ProjectDetail } from './models/ProjectDetail';
export type { ProjectListResponse } from './models/ProjectListResponse';
export type { ProjectSummary } from './models/ProjectSummary';
export type { ProjectTemplateCreateRequest } from './models/ProjectTemplateCreateRequest';
export type { ProjectTemplateListResponse } from './models/ProjectTemplateListResponse';
export type { ProjectTemplateResponse } from './models/ProjectTemplateResponse';
export type { ProjectTemplateUpdateRequest } from './models/ProjectTemplateUpdateRequest';
export type { ProjectUpdateRequest } from './models/ProjectUpdateRequest';
export type { PromoteRequest } from './models/PromoteRequest';
export type { PublishRequest } from './models/PublishRequest';
export type { PublishResponse } from './models/PublishResponse';
export type { RefreshJobStatus } from './models/RefreshJobStatus';
export type { RefreshModeEnum } from './models/RefreshModeEnum';
export type { RefreshRequest } from './models/RefreshRequest';
export type { ReimportRequest } from './models/ReimportRequest';
export type { ReimportResponse } from './models/ReimportResponse';
export type { ReorderArtifactsRequest } from './models/ReorderArtifactsRequest';
export type { RollbackRequest } from './models/RollbackRequest';
export type { RollbackResponse } from './models/RollbackResponse';
export type { RollbackSafetyAnalysisResponse } from './models/RollbackSafetyAnalysisResponse';
export type { ScanRequest } from './models/ScanRequest';
export type { ScanResultDTO } from './models/ScanResultDTO';
export type { ScoreBreakdown } from './models/ScoreBreakdown';
export type { SearchResult } from './models/SearchResult';
export type { SearchResultsResponse } from './models/SearchResultsResponse';
export type { ShareLinkDeleteResponse } from './models/ShareLinkDeleteResponse';
export type { ShareLinkResponse } from './models/ShareLinkResponse';
export type { ShareLinkUpdateRequest } from './models/ShareLinkUpdateRequest';
export type { skillmeat__api__schemas__artifacts__FileContentResponse } from './models/skillmeat__api__schemas__artifacts__FileContentResponse';
export type { skillmeat__api__schemas__collections__ArtifactSummary } from './models/skillmeat__api__schemas__collections__ArtifactSummary';
export type { skillmeat__api__schemas__collections__CollectionArtifactsResponse } from './models/skillmeat__api__schemas__collections__CollectionArtifactsResponse';
export type { skillmeat__api__schemas__deployments__DeploymentResponse } from './models/skillmeat__api__schemas__deployments__DeploymentResponse';
export type { skillmeat__api__schemas__marketplace__FileContentResponse } from './models/skillmeat__api__schemas__marketplace__FileContentResponse';
export type { skillmeat__api__schemas__mcp__DeploymentResponse } from './models/skillmeat__api__schemas__mcp__DeploymentResponse';
export type { skillmeat__api__schemas__user_collections__ArtifactSummary } from './models/skillmeat__api__schemas__user_collections__ArtifactSummary';
export type { skillmeat__api__schemas__user_collections__CollectionArtifactsResponse } from './models/skillmeat__api__schemas__user_collections__CollectionArtifactsResponse';
export type { SkipClearResponse } from './models/SkipClearResponse';
export type { SkipPreferenceAddRequest } from './models/SkipPreferenceAddRequest';
export type { SkipPreferenceListResponse } from './models/SkipPreferenceListResponse';
export type { SkipPreferenceResponse } from './models/SkipPreferenceResponse';
export type { SnapshotCreateRequest } from './models/SnapshotCreateRequest';
export type { SnapshotCreateResponse } from './models/SnapshotCreateResponse';
export type { SnapshotListResponse } from './models/SnapshotListResponse';
export type { SnapshotResponse } from './models/SnapshotResponse';
export type { SourceListResponse } from './models/SourceListResponse';
export type { SourceResponse } from './models/SourceResponse';
export type { StaleArtifactResponse } from './models/StaleArtifactResponse';
export type { StaleArtifactsListResponse } from './models/StaleArtifactsListResponse';
export type { SyncConflictResponse } from './models/SyncConflictResponse';
export type { SyncPullRequest } from './models/SyncPullRequest';
export type { SyncPushRequest } from './models/SyncPushRequest';
export type { SyncResolveRequest } from './models/SyncResolveRequest';
export type { SyncResultResponse } from './models/SyncResultResponse';
export type { SyncStatusResponse } from './models/SyncStatusResponse';
export type { TagCreateRequest } from './models/TagCreateRequest';
export type { TagListResponse } from './models/TagListResponse';
export type { TagResponse } from './models/TagResponse';
export type { TagUpdateRequest } from './models/TagUpdateRequest';
export type { TemplateEntitySchema } from './models/TemplateEntitySchema';
export type { TemplateVariableValue } from './models/TemplateVariableValue';
export type { TopArtifactItem } from './models/TopArtifactItem';
export type { TopArtifactsResponse } from './models/TopArtifactsResponse';
export type { TrendDataPoint } from './models/TrendDataPoint';
export type { TrendsResponse } from './models/TrendsResponse';
export type { UndeployRequest } from './models/UndeployRequest';
export type { UndeployResponse } from './models/UndeployResponse';
export type { UpdateAutoTagRequest } from './models/UpdateAutoTagRequest';
export type { UpdateAutoTagResponse } from './models/UpdateAutoTagResponse';
export type { UpdateCatalogEntryNameRequest } from './models/UpdateCatalogEntryNameRequest';
export type { UpdateSegmentStatusRequest } from './models/UpdateSegmentStatusRequest';
export type { UpdateSegmentStatusResponse } from './models/UpdateSegmentStatusResponse';
export type { UpdateSourceRequest } from './models/UpdateSourceRequest';
export type { UserCollectionCreateRequest } from './models/UserCollectionCreateRequest';
export type { UserCollectionListResponse } from './models/UserCollectionListResponse';
export type { UserCollectionResponse } from './models/UserCollectionResponse';
export type { UserCollectionUpdateRequest } from './models/UserCollectionUpdateRequest';
export type { UserCollectionWithGroupsResponse } from './models/UserCollectionWithGroupsResponse';
export type { UserRatingRequest } from './models/UserRatingRequest';
export type { UserRatingResponse } from './models/UserRatingResponse';
export type { ValidationError } from './models/ValidationError';
export type { ValidationErrorDetail } from './models/ValidationErrorDetail';
export type { ValidationIssueResponse } from './models/ValidationIssueResponse';
export type { VersionDiffRequest } from './models/VersionDiffRequest';
export type { VersionDiffResponse } from './models/VersionDiffResponse';
export type { VersionGraphNodeResponse } from './models/VersionGraphNodeResponse';
export type { VersionGraphResponse } from './models/VersionGraphResponse';

export { AnalyticsService } from './services/AnalyticsService';
export { ArtifactsService } from './services/ArtifactsService';
export { BundlesService } from './services/BundlesService';
export { CacheService } from './services/CacheService';
export { CollectionsService } from './services/CollectionsService';
export { ConfigService } from './services/ConfigService';
export { ContextEntitiesService } from './services/ContextEntitiesService';
export { ContextModulesService } from './services/ContextModulesService';
export { ContextPacksService } from './services/ContextPacksService';
export { ContextSyncService } from './services/ContextSyncService';
export { DeploymentsService } from './services/DeploymentsService';
export { DiscoveryService } from './services/DiscoveryService';
export { GroupsService } from './services/GroupsService';
export { HealthService } from './services/HealthService';
export { MarketplaceService } from './services/MarketplaceService';
export { MarketplaceCatalogService } from './services/MarketplaceCatalogService';
export { MarketplaceSourcesService } from './services/MarketplaceSourcesService';
export { MatchService } from './services/MatchService';
export { McpService } from './services/McpService';
export { MemoryItemsService } from './services/MemoryItemsService';
export { MergeService } from './services/MergeService';
export { MetricsService } from './services/MetricsService';
export { ProjectsService } from './services/ProjectsService';
export { ProjectTemplatesService } from './services/ProjectTemplatesService';
export { RatingsService } from './services/RatingsService';
export { RootService } from './services/RootService';
export { SettingsService } from './services/SettingsService';
export { TagsService } from './services/TagsService';
export { UserCollectionsService } from './services/UserCollectionsService';
export { VersionsService } from './services/VersionsService';
