"""API routers package.

This package contains all API route handlers organized by domain.
"""

from . import (
    analytics,
    artifacts,
    bundles,
    cache,
    collections,
    config,
    context_entities,
    context_modules,
    context_packing,
    context_sync,
    deployment_profiles,
    deployments,
    groups,
    health,
    marketplace,
    marketplace_catalog,
    marketplace_sources,
    match,
    mcp,
    memory_items,
    merge,
    project_templates,
    projects,
    ratings,
    settings,
    tags,
    user_collections,
    versions,
)

__all__ = [
    "analytics",
    "artifacts",
    "bundles",
    "cache",
    "collections",
    "config",
    "context_entities",
    "context_modules",
    "context_packing",
    "context_sync",
    "deployment_profiles",
    "deployments",
    "groups",
    "health",
    "marketplace",
    "marketplace_catalog",
    "marketplace_sources",
    "match",
    "mcp",
    "memory_items",
    "merge",
    "project_templates",
    "projects",
    "ratings",
    "settings",
    "tags",
    "user_collections",
    "versions",
]
