#!/usr/bin/env bash
set -uo pipefail

# Generated by CCDash Settings > Projects > Testing
# Project: SkillMeat
# Project ID: 3df0ff70-85fd-402f-a028-83cae8bcedc2
# Generated: 2026-03-01T20:14:55.661Z

PROJECT_ROOT="${1:-$(pwd)}"
if ! cd "$PROJECT_ROOT"; then
  echo "[error] Unable to cd to project root: $PROJECT_ROOT"
  exit 1
fi
PROJECT_ROOT="$(pwd)"

RUN_BACKEND="${CCDASH_RUN_BACKEND:-1}"
RUN_FRONTEND_UNIT="${CCDASH_RUN_FRONTEND_UNIT:-1}"
RUN_E2E="${CCDASH_RUN_E2E:-1}"
RUN_PERF="${CCDASH_RUN_PERF:-1}"
RUN_LOAD="${CCDASH_RUN_LOAD:-1}"
RUN_TRIAGE="${CCDASH_RUN_TRIAGE:-1}"

E2E_PROJECT="${CCDASH_E2E_PROJECT:-chromium}"
E2E_MAX_FAILURES="${CCDASH_E2E_MAX_FAILURES:-10}"
E2E_TIMEOUT_SECONDS="${CCDASH_E2E_TIMEOUT_SECONDS:-1800}"
E2E_TARGET="${CCDASH_E2E_TARGET:-tests/e2e}"

DEFAULT_RESULTS_DIR="${CCDASH_RESULTS_DIR:-test-results}"
FALLBACK_RESULTS_DIR=".ccdash/test-results"

is_writable_dir() {
  local dir="$1"
  local probe
  mkdir -p "$dir" 2>/dev/null || return 1
  probe="$dir/.ccdash-write-test.$$"
  ( : > "$probe" ) 2>/dev/null || return 1
  rm -f "$probe"
  return 0
}

choose_results_dir() {
  local preferred="$1"
  local fallback="$2"
  if is_writable_dir "$preferred"; then
    echo "$preferred"
    return 0
  fi
  echo "[warn] Result directory is not writable: $preferred" >&2
  echo "[warn] Falling back to writable result directory: $fallback" >&2
  mkdir -p "$fallback"
  echo "$fallback"
}

RESULTS_DIR="$(choose_results_dir "$DEFAULT_RESULTS_DIR" "$FALLBACK_RESULTS_DIR")"
RESULTS_ABS="$PROJECT_ROOT/$RESULTS_DIR"

BACKEND_DIR="$RESULTS_ABS/backend"
FRONTEND_UNIT_DIR="$RESULTS_ABS/frontend-unit"
E2E_DIR="$RESULTS_ABS/e2e"
PERF_DIR="$RESULTS_ABS/perf"
TRIAGE_DIR="$RESULTS_ABS/triage"

# Remove stale artifacts from previous runs so triage reflects the current run.
rm -rf "$BACKEND_DIR" "$FRONTEND_UNIT_DIR" "$E2E_DIR" "$PERF_DIR" "$TRIAGE_DIR"
mkdir -p "$BACKEND_DIR" "$FRONTEND_UNIT_DIR" "$E2E_DIR" "$PERF_DIR" "$TRIAGE_DIR"

WEB_DIR="$PROJECT_ROOT/skillmeat/web"

PYTEST_CMD=()
PYTHON_CMD=()

if command -v uv >/dev/null 2>&1 && uv run python -c "import sys; sys.exit(0)" >/dev/null 2>&1; then
  PYTHON_CMD=(uv run python)
elif [ -x "$PROJECT_ROOT/.venv/bin/python" ]; then
  PYTHON_CMD=("$PROJECT_ROOT/.venv/bin/python")
elif command -v python3 >/dev/null 2>&1; then
  PYTHON_CMD=(python3)
elif command -v python >/dev/null 2>&1; then
  PYTHON_CMD=(python)
fi

if command -v uv >/dev/null 2>&1 && uv run python -c "import pytest" >/dev/null 2>&1; then
  PYTEST_CMD=(uv run pytest)
elif [ -x "$PROJECT_ROOT/.venv/bin/python" ] && "$PROJECT_ROOT/.venv/bin/python" -c "import pytest" >/dev/null 2>&1; then
  PYTEST_CMD=("$PROJECT_ROOT/.venv/bin/python" -m pytest)
elif [ "${#PYTHON_CMD[@]}" -gt 0 ] && "${PYTHON_CMD[@]}" -c "import pytest" >/dev/null 2>&1; then
  PYTEST_CMD=("${PYTHON_CMD[@]}" -m pytest)
elif command -v pytest >/dev/null 2>&1; then
  PYTEST_CMD=(pytest)
fi

export PYTHONPATH="$PROJECT_ROOT${PYTHONPATH:+:$PYTHONPATH}"

run_step() {
  local label="$1"
  local log_file="$2"
  shift 2
  echo "[run] $label"
  "$@" >"$log_file" 2>&1
  local rc=$?
  if [ "$rc" -eq 0 ]; then
    echo "[ok] $label"
  else
    echo "[warn] $label failed (exit $rc). Log: $log_file"
  fi
  return "$rc"
}

run_step_with_timeout() {
  local label="$1"
  local log_file="$2"
  local timeout_seconds="$3"
  shift 3

  echo "[run] $label (timeout: ${timeout_seconds}s)"
  "$@" >"$log_file" 2>&1 &
  local cmd_pid=$!

  (
    sleep "$timeout_seconds"
    if kill -0 "$cmd_pid" 2>/dev/null; then
      echo "[warn] $label exceeded timeout (${timeout_seconds}s). Terminating process..." >> "$log_file"
      kill -TERM "$cmd_pid" 2>/dev/null || true
      sleep 5
      kill -KILL "$cmd_pid" 2>/dev/null || true
    fi
  ) &
  local watchdog_pid=$!

  wait "$cmd_pid"
  local rc=$?

  kill "$watchdog_pid" 2>/dev/null || true
  wait "$watchdog_pid" 2>/dev/null || true

  if [ "$rc" -eq 0 ]; then
    echo "[ok] $label"
  elif [ "$rc" -eq 137 ] || [ "$rc" -eq 143 ]; then
    echo "[warn] $label timed out (exit $rc). Log: $log_file"
  else
    echo "[warn] $label failed (exit $rc). Log: $log_file"
  fi
  return "$rc"
}

status_from_rc() {
  if [ "$1" -eq 0 ]; then
    echo "PASS"
  else
    echo "FAIL"
  fi
}

record_suite() {
  local suite="$1"
  local status="$2"
  local exit_code="$3"
  local artifacts="$4"
  printf "%s\t%s\t%s\t%s\n" "$suite" "$status" "$exit_code" "$artifacts" >> "$SUMMARY_TSV"
}

ensure_file() {
  local file_path="$1"
  local fallback_content="$2"
  if [ ! -f "$file_path" ]; then
    printf "%s\n" "$fallback_content" > "$file_path"
  fi
}

echo "[info] Project root: $PROJECT_ROOT"
echo "[info] Test artifacts output directory: $RESULTS_DIR"

SUMMARY_TSV="$TRIAGE_DIR/suite-status.tsv"
: > "$SUMMARY_TSV"

overall_failures=0

# Backend (pytest + coverage)
backend_rc=0
if [ "$RUN_BACKEND" = "1" ]; then
  if [ "${#PYTEST_CMD[@]}" -eq 0 ]; then
    backend_rc=127
    echo "[warn] No Python test runner found for backend suite."
  else
    run_step \
      "backend: pytest (JUnit + coverage XML/JSON)" \
      "$BACKEND_DIR/pytest.log" \
      "${PYTEST_CMD[@]}" \
      -v \
      --junitxml "$BACKEND_DIR/pytest-junit.xml" \
      --cov=skillmeat \
      --cov-report "xml:$BACKEND_DIR/coverage.xml" \
      --cov-report "json:$BACKEND_DIR/coverage.json"
    backend_rc=$?
  fi
  ensure_file "$BACKEND_DIR/pytest-junit.xml" '<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"/>'
  ensure_file "$BACKEND_DIR/coverage.xml" '<?xml version="1.0" ?><coverage version="0.0" timestamp="0" lines-valid="0" lines-covered="0" line-rate="0"/>'
  ensure_file "$BACKEND_DIR/coverage.json" '{"meta": {"note": "coverage output missing"}, "files": {}, "totals": {}}'
  record_suite "backend-pytest" "$(status_from_rc "$backend_rc")" "$backend_rc" "$BACKEND_DIR/pytest-junit.xml,$BACKEND_DIR/coverage.xml,$BACKEND_DIR/coverage.json"
else
  echo "[skip] backend suite disabled (CCDASH_RUN_BACKEND=0)"
  record_suite "backend-pytest" "SKIPPED" "0" "-"
fi

# Frontend unit (Jest)
frontend_unit_rc=0
if [ "$RUN_FRONTEND_UNIT" = "1" ]; then
  if ! command -v pnpm >/dev/null 2>&1; then
    frontend_unit_rc=127
    echo "[warn] pnpm not found; skipping frontend unit suite."
  elif [ ! -d "$WEB_DIR" ]; then
    frontend_unit_rc=127
    echo "[warn] Web directory not found: $WEB_DIR"
  else
    run_step \
      "frontend-unit: jest JSON + coverage" \
      "$FRONTEND_UNIT_DIR/jest.log" \
      env CI=1 pnpm --dir "$WEB_DIR" exec jest \
      --coverage \
      --coverageDirectory "$FRONTEND_UNIT_DIR/coverage" \
      --coverageReporters=json \
      --coverageReporters=lcov \
      --coverageReporters=html \
      --json \
      --outputFile "$FRONTEND_UNIT_DIR/jest-results.json"
    frontend_unit_rc=$?
  fi
  ensure_file "$FRONTEND_UNIT_DIR/jest-results.json" '{"success": false, "numFailedTests": 0, "testResults": []}'
  record_suite "frontend-jest" "$(status_from_rc "$frontend_unit_rc")" "$frontend_unit_rc" "$FRONTEND_UNIT_DIR/jest-results.json,$FRONTEND_UNIT_DIR/coverage"
else
  echo "[skip] frontend unit suite disabled (CCDASH_RUN_FRONTEND_UNIT=0)"
  record_suite "frontend-jest" "SKIPPED" "0" "-"
fi

# Frontend e2e (Playwright)
e2e_rc=0
if [ "$RUN_E2E" = "1" ]; then
  if ! command -v pnpm >/dev/null 2>&1; then
    e2e_rc=127
    echo "[warn] pnpm not found; skipping e2e suite."
  elif [ ! -d "$WEB_DIR" ]; then
    e2e_rc=127
    echo "[warn] Web directory not found: $WEB_DIR"
  else
    run_step_with_timeout \
      "e2e: playwright test (target=$E2E_TARGET, project=$E2E_PROJECT, max-failures=$E2E_MAX_FAILURES)" \
      "$E2E_DIR/playwright.log" \
      "$E2E_TIMEOUT_SECONDS" \
      env \
      CI=1 \
      PLAYWRIGHT_JSON_OUTPUT_FILE="$E2E_DIR/results.json" \
      PLAYWRIGHT_HTML_OUTPUT_DIR="$E2E_DIR/playwright-report" \
      PLAYWRIGHT_HTML_OPEN=never \
      pnpm --dir "$WEB_DIR" exec playwright test \
      "$E2E_TARGET" \
      --project "$E2E_PROJECT" \
      --max-failures "$E2E_MAX_FAILURES" \
      --output "$E2E_DIR/pw-output"
    e2e_rc=$?
  fi

  if [ ! -f "$E2E_DIR/results.json" ] && [ -f "$WEB_DIR/test-results/results.json" ]; then
    cp -f "$WEB_DIR/test-results/results.json" "$E2E_DIR/results.json"
  fi
  if [ ! -d "$E2E_DIR/playwright-report" ] && [ -d "$WEB_DIR/playwright-report" ]; then
    rm -rf "$E2E_DIR/playwright-report"
    cp -R "$WEB_DIR/playwright-report" "$E2E_DIR/playwright-report"
  fi
  ensure_file "$E2E_DIR/results.json" '{"config": {}, "suites": []}'
  record_suite "frontend-playwright" "$(status_from_rc "$e2e_rc")" "$e2e_rc" "$E2E_DIR/results.json,$E2E_DIR/playwright-report"
else
  echo "[skip] e2e suite disabled (CCDASH_RUN_E2E=0)"
  record_suite "frontend-playwright" "SKIPPED" "0" "-"
fi

# Performance (benchmark + lighthouse)
perf_pytest_rc=0
perf_api_rc=0
perf_ops_rc=0
perf_lighthouse_rc=0

if [ "$RUN_PERF" = "1" ]; then
  if [ "${#PYTEST_CMD[@]}" -eq 0 ]; then
    perf_pytest_rc=127
    echo "[warn] No Python test runner found for pytest benchmark."
  else
    run_step \
      "perf: pytest benchmark JSON" \
      "$PERF_DIR/pytest-benchmark.log" \
      "${PYTEST_CMD[@]}" \
      -v \
      tests/performance \
      --benchmark-only \
      --benchmark-json "$PERF_DIR/pytest-benchmark.json"
    perf_pytest_rc=$?
  fi
  ensure_file "$PERF_DIR/pytest-benchmark.json" '{"benchmarks": [], "machine_info": {}, "commit_info": {}}'
  record_suite "perf-pytest-benchmark" "$(status_from_rc "$perf_pytest_rc")" "$perf_pytest_rc" "$PERF_DIR/pytest-benchmark.json"

  if [ "${#PYTHON_CMD[@]}" -eq 0 ]; then
    perf_api_rc=127
    perf_ops_rc=127
    echo "[warn] No Python runtime found for benchmark scripts."
  else
    run_step \
      "perf: API benchmark JSON" \
      "$PERF_DIR/benchmark-api.log" \
      "${PYTHON_CMD[@]}" \
      "$PROJECT_ROOT/tests/performance/benchmark_api.py" \
      --check-server \
      --samples 20 \
      --output "$PERF_DIR/benchmark-api.json"
    perf_api_rc=$?

    run_step \
      "perf: operation benchmark JSON" \
      "$PERF_DIR/benchmark-operations.log" \
      "${PYTHON_CMD[@]}" \
      "$PROJECT_ROOT/tests/performance/benchmark_operations.py" \
      --iterations 3 \
      --output "$PERF_DIR/benchmark-operations.json"
    perf_ops_rc=$?
  fi
  ensure_file "$PERF_DIR/benchmark-api.json" '{"endpoints": [], "sla_violations": []}'
  ensure_file "$PERF_DIR/benchmark-operations.json" '{"results": []}'
  record_suite "perf-api-benchmark" "$(status_from_rc "$perf_api_rc")" "$perf_api_rc" "$PERF_DIR/benchmark-api.json"
  record_suite "perf-ops-benchmark" "$(status_from_rc "$perf_ops_rc")" "$perf_ops_rc" "$PERF_DIR/benchmark-operations.json"

  if ! command -v pnpm >/dev/null 2>&1; then
    perf_lighthouse_rc=127
    echo "[warn] pnpm not found; skipping lighthouse run."
  elif [ ! -d "$WEB_DIR" ]; then
    perf_lighthouse_rc=127
    echo "[warn] Web directory not found: $WEB_DIR"
  else
    run_step \
      "perf: lighthouse (HTML + JSON)" \
      "$PERF_DIR/lighthouse.log" \
      env CI=1 pnpm --dir "$WEB_DIR" exec node tests/performance/lighthouse.js
    perf_lighthouse_rc=$?

    mkdir -p "$PERF_DIR/lighthouse"
    if ls "$WEB_DIR"/lighthouse-reports/*.json >/dev/null 2>&1; then
      cp -f "$WEB_DIR"/lighthouse-reports/*.json "$PERF_DIR/lighthouse/"
    fi
    if ls "$WEB_DIR"/lighthouse-reports/*.html >/dev/null 2>&1; then
      cp -f "$WEB_DIR"/lighthouse-reports/*.html "$PERF_DIR/lighthouse/"
    fi
  fi
  record_suite "perf-lighthouse" "$(status_from_rc "$perf_lighthouse_rc")" "$perf_lighthouse_rc" "$PERF_DIR/lighthouse"
else
  echo "[skip] performance suites disabled (CCDASH_RUN_PERF=0)"
  record_suite "perf-pytest-benchmark" "SKIPPED" "0" "-"
  record_suite "perf-api-benchmark" "SKIPPED" "0" "-"
  record_suite "perf-ops-benchmark" "SKIPPED" "0" "-"
  record_suite "perf-lighthouse" "SKIPPED" "0" "-"
fi

# Load (Locust)
load_rc=0
if [ "$RUN_LOAD" = "1" ]; then
  if ! command -v locust >/dev/null 2>&1; then
    load_rc=127
    echo "[warn] locust not found; skipping load test suite."
  else
    mkdir -p "$PERF_DIR/locust"
    run_step \
      "load: locust (CSV + HTML)" \
      "$PERF_DIR/locust/locust.log" \
      locust \
      -f "$PROJECT_ROOT/tests/performance/locustfile.py" \
      --headless \
      --users 5 \
      --spawn-rate 1 \
      --run-time 30s \
      --host http://localhost:8000 \
      --csv "$PERF_DIR/locust/locust" \
      --html "$PERF_DIR/locust/locust-report.html"
    load_rc=$?
  fi
  record_suite "load-locust" "$(status_from_rc "$load_rc")" "$load_rc" "$PERF_DIR/locust"
else
  echo "[skip] load suite disabled (CCDASH_RUN_LOAD=0)"
  record_suite "load-locust" "SKIPPED" "0" "-"
fi

# Failure triage (JSON + Markdown + text)
triage_rc=0
if [ "$RUN_TRIAGE" = "1" ]; then
  if [ "${#PYTHON_CMD[@]}" -eq 0 ]; then
    triage_rc=127
    echo "[warn] No Python runtime found for failure triage."
  elif [ ! -f "$PROJECT_ROOT/scripts/parse_test_failures.py" ]; then
    triage_rc=127
    echo "[warn] Missing parser script: $PROJECT_ROOT/scripts/parse_test_failures.py"
  else
    echo "[run] triage: parse test failures"
    (
      cd "$TRIAGE_DIR" || exit 1
      "${PYTHON_CMD[@]}" "$PROJECT_ROOT/scripts/parse_test_failures.py" \
        --input-dir "$RESULTS_ABS" \
        --output "$TRIAGE_DIR/test-failures.json" \
        >"$TRIAGE_DIR/parse-test-failures.log" 2>&1
    )
    triage_rc=$?
    if [ "$triage_rc" -eq 0 ]; then
      echo "[ok] triage: parse test failures"
    else
      echo "[warn] triage: parse test failures exited $triage_rc (expected when failures are found). Log: $TRIAGE_DIR/parse-test-failures.log"
    fi
  fi
  ensure_file "$TRIAGE_DIR/test-failures.json" '{"total_failures": 0, "by_framework": {}, "by_suite": {}, "failures": []}'
  ensure_file "$TRIAGE_DIR/test-failures.md" 'No test failures detected.'
  ensure_file "$TRIAGE_DIR/test-failures-summary.txt" 'Total failures: 0'
  record_suite "failure-triage" "$(status_from_rc "$triage_rc")" "$triage_rc" "$TRIAGE_DIR/test-failures.json,$TRIAGE_DIR/test-failures.md,$TRIAGE_DIR/test-failures-summary.txt"
else
  echo "[skip] failure triage disabled (CCDASH_RUN_TRIAGE=0)"
  record_suite "failure-triage" "SKIPPED" "0" "-"
fi

if [ "${#PYTHON_CMD[@]}" -gt 0 ]; then
  "${PYTHON_CMD[@]}" - "$SUMMARY_TSV" "$TRIAGE_DIR/ccdash-suite-summary.json" "$TRIAGE_DIR/ccdash-suite-summary.md" "$TRIAGE_DIR/ccdash-suite-summary.txt" <<'PY'
import json
import sys
from pathlib import Path

tsv_path = Path(sys.argv[1])
json_path = Path(sys.argv[2])
md_path = Path(sys.argv[3])
txt_path = Path(sys.argv[4])

entries = []
for line in tsv_path.read_text().splitlines():
    parts = line.split("\t")
    if len(parts) != 4:
        continue
    suite, status, exit_code, artifacts = parts
    entries.append({
        "suite": suite,
        "status": status,
        "exit_code": int(exit_code),
        "artifacts": [a for a in artifacts.split(",") if a and a != "-"],
    })

overall_status = "PASS"
if any(e["status"] == "FAIL" for e in entries):
    overall_status = "FAIL"

json_payload = {
    "overall_status": overall_status,
    "suite_count": len(entries),
    "suites": entries,
}
json_path.write_text(json.dumps(json_payload, indent=2))

md_lines = [
    "## CCDash Test Suite Summary",
    "",
    f"Overall status: **{overall_status}**",
    "",
    "| Suite | Status | Exit Code |",
    "| --- | --- | --- |",
]
for entry in entries:
    md_lines.append(f"| {entry['suite']} | {entry['status']} | {entry['exit_code']} |")
md_lines.append("")
md_lines.append("Artifacts are available in this result tree.")
md_path.write_text("\n".join(md_lines) + "\n")

txt_lines = [f"Overall status: {overall_status}", ""]
for entry in entries:
    txt_lines.append(f"{entry['suite']}: {entry['status']} (exit {entry['exit_code']})")
txt_path.write_text("\n".join(txt_lines) + "\n")
PY
else
  cp -f "$SUMMARY_TSV" "$TRIAGE_DIR/ccdash-suite-summary.txt"
  printf '{"overall_status":"UNKNOWN","suite_count":0,"suites":[]}\n' > "$TRIAGE_DIR/ccdash-suite-summary.json"
  {
    echo "## CCDash Test Suite Summary"
    echo
    echo "Overall status: **UNKNOWN**"
    echo
    echo "Suite status TSV was generated but Python was unavailable to render JSON/Markdown summary."
  } > "$TRIAGE_DIR/ccdash-suite-summary.md"
fi

while IFS=$'\t' read -r _suite _status _exit _artifacts; do
  if [ "$_status" = "FAIL" ]; then
    overall_failures=$((overall_failures + 1))
  fi
done < "$SUMMARY_TSV"

echo "[done] Test artifact setup and execution complete."
echo "[info] Result directory: $RESULTS_ABS"
echo "[info] Summary JSON: $TRIAGE_DIR/ccdash-suite-summary.json"
echo "[info] Failure triage JSON: $TRIAGE_DIR/test-failures.json"
echo "[next] In CCDash Settings: point paths to $RESULTS_DIR, validate, then run Sync Now."

# Keep script non-blocking for ingestion; inspect summary artifacts for failures.
exit 0
