"""Consolidated initial schema

Revision ID: 001_consolidated_schema
Revises:
Create Date: 2026-03-09

This migration creates the complete database schema for SkillMeat,
consolidating 65 incremental migrations into a single initial schema.
Includes 43 tables, updated_at triggers (dialect-aware), and FTS5
virtual tables (SQLite only).
"""

from __future__ import annotations

import logging
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from skillmeat.cache.migrations.dialect_helpers import (
    is_sqlite,
    create_updated_at_trigger,
    drop_updated_at_trigger,
)

revision: str = "001_consolidated_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = logging.getLogger(__name__)

# Tables that need updated_at triggers (in creation order)
_TRIGGER_TABLES = [
    "projects",
    "artifacts",
    "collections",
    "groups",
    "marketplace_sources",
    "project_templates",
    "marketplace_catalog_entries",
    "tags",
    "memory_items",
    "composite_artifacts",
    "context_modules",
    "deployment_profiles",
    "deployment_sets",
    "duplicate_pairs",
    "entity_categories",
    "entity_type_configs",
    "execution_steps",
    "teams",
    "users",
    "workflow_executions",
    "workflow_stages",
    "workflows",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_metadata',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('collection_type', sa.String(), nullable=True),
    sa.Column('context_category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.CheckConstraint('length(name) > 0 AND length(name) <= 255', name='check_collection_name_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collections_created_at', 'collections', ['created_at'], unique=False)
    op.create_index('idx_collections_created_by', 'collections', ['created_by'], unique=False)
    op.create_index('idx_collections_name', 'collections', ['name'], unique=False)
    op.create_index('idx_collections_type', 'collections', ['collection_type'], unique=False)
    op.create_table('community_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('imported_from', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'source', name='uq_community_score')
    )
    op.create_index('idx_community_scores_artifact_id', 'community_scores', ['artifact_id'], unique=False)
    op.create_table('composite_artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('composite_type', sa.String(), server_default='plugin', nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("composite_type IN ('plugin', 'stack', 'suite', 'skill')", name='check_composite_artifact_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_composite_artifacts_collection_id', 'composite_artifacts', ['collection_id'], unique=False)
    op.create_index('idx_composite_artifacts_composite_type', 'composite_artifacts', ['composite_type'], unique=False)
    op.create_table('custom_colors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hex', sa.String(length=7), nullable=False, comment="CSS hex color string including leading '#', e.g. #7c3aed"),
    sa.Column('name', sa.String(length=64), nullable=True, comment='Optional human-readable label for the color'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("hex LIKE '#______' OR hex LIKE '#___'", name='check_custom_color_hex_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hex')
    )
    op.create_index('idx_custom_colors_hex', 'custom_colors', ['hex'], unique=True)
    op.create_table('deployment_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('tags_json', sa.Text(), server_default='[]', nullable=False, comment='JSON-serialized list of tag strings'),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('remote_url', sa.Text(), nullable=True, comment='Remote Git repository URL for remote_git platform deployments'),
    sa.Column('provisioned_by', sa.String(length=128), nullable=True, comment="Audit field: provisioning agent/system (e.g. 'idp', 'backstage')"),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(name) > 0 AND length(name) <= 255', name='check_deployment_set_name_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deployment_sets_created_at', 'deployment_sets', ['created_at'], unique=False)
    op.create_index('idx_deployment_sets_owner_id', 'deployment_sets', ['owner_id'], unique=False)
    op.create_table('duplicate_pairs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('artifact1_uuid', sa.String(length=32), nullable=False, comment='UUID of the first artifact in the similar pair'),
    sa.Column('artifact2_uuid', sa.String(length=32), nullable=False, comment='UUID of the second artifact in the similar pair'),
    sa.Column('similarity_score', sa.Float(), nullable=False, comment='Normalised similarity score in the range [0.0, 1.0]'),
    sa.Column('match_reasons', sa.Text(), server_default='[]', nullable=True, comment='JSON-encoded list of human-readable match reason strings'),
    sa.Column('ignored', sa.Boolean(), server_default='0', nullable=False, comment='True when the user has dismissed this pair from the UI'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('similarity_score >= 0.0 AND similarity_score <= 1.0', name='check_duplicate_pair_score'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact1_uuid', 'artifact2_uuid', name='uq_duplicate_pair_artifacts')
    )
    op.create_index('idx_duplicate_pairs_artifact1', 'duplicate_pairs', ['artifact1_uuid'], unique=False)
    op.create_index('idx_duplicate_pairs_artifact2', 'duplicate_pairs', ['artifact2_uuid'], unique=False)
    op.create_index('idx_duplicate_pairs_ignored', 'duplicate_pairs', ['ignored'], unique=False)
    op.create_table('entity_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable label shown in the UI'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment="URL-safe machine identifier, e.g. 'testing-utilities'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional longer description of the category'),
    sa.Column('color', sa.String(length=7), nullable=True, comment="Hex colour code for UI badge rendering, e.g. '#3B82F6'"),
    sa.Column('entity_type_slug', sa.String(length=50), nullable=True, comment='When set, restrict this category to artifacts of this entity type'),
    sa.Column('platform', sa.String(length=50), nullable=True, comment='When set, restrict this category to artifacts targeting this platform'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_builtin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_categories_entity_type_platform', 'entity_categories', ['entity_type_slug', 'platform'], unique=False)
    op.create_index('idx_entity_categories_is_builtin', 'entity_categories', ['is_builtin'], unique=False)
    op.create_index('idx_entity_categories_sort_order', 'entity_categories', ['sort_order'], unique=False)
    op.create_index(op.f('ix_entity_categories_slug'), 'entity_categories', ['slug'], unique=True)
    op.create_table('entity_type_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True, comment="Optional hex color code for UI card indicators (e.g. '#3B82F6')"),
    sa.Column('path_prefix', sa.String(), nullable=True),
    sa.Column('example_path', sa.String(), nullable=True),
    sa.Column('required_frontmatter_keys', sa.JSON(), nullable=True),
    sa.Column('optional_frontmatter_keys', sa.JSON(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('content_template', sa.Text(), nullable=True),
    sa.Column('applicable_platforms', sa.JSON(), nullable=True, comment='JSON list of platform slugs this type applies to. None means applicable to all platforms.'),
    sa.Column('frontmatter_schema', sa.JSON(), nullable=True, comment='JSON Schema subset for validating custom type frontmatter. Structure: {"required": ["key1"], "properties": {"key1": {"type": "string"}}}'),
    sa.Column('is_builtin', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_type_configs_is_builtin', 'entity_type_configs', ['is_builtin'], unique=False)
    op.create_index('idx_entity_type_configs_sort_order', 'entity_type_configs', ['sort_order'], unique=False)
    op.create_index(op.f('ix_entity_type_configs_slug'), 'entity_type_configs', ['slug'], unique=True)
    op.create_table('github_repo_cache',
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index('idx_github_repo_cache_fetched_at', 'github_repo_cache', ['fetched_at'], unique=False)
    op.create_table('marketplace',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.CheckConstraint("type IN ('skill', 'command', 'agent', 'mcp', 'mcp_server', 'hook', 'project_config', 'spec_file', 'rule_file', 'context_file', 'progress_template')", name='check_marketplace_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), server_default='main', nullable=False),
    sa.Column('root_hint', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True, comment='User-provided description for this source'),
    sa.Column('notes', sa.String(length=2000), nullable=True, comment='Internal notes/documentation for this source'),
    sa.Column('repo_description', sa.String(length=2000), nullable=True, comment='Description fetched from GitHub API'),
    sa.Column('repo_readme', sa.Text(), nullable=True, comment='README content from GitHub (up to 50KB)'),
    sa.Column('tags', sa.Text(), nullable=True, comment='JSON-serialized list of tags for categorization'),
    sa.Column('auto_tags', sa.Text(), nullable=True, comment='JSON: {extracted: [{value, normalized, status, source}]} for GitHub topics'),
    sa.Column('manual_map', sa.Text(), nullable=True),
    sa.Column('access_token_id', sa.String(), nullable=True),
    sa.Column('trust_level', sa.String(), server_default='basic', nullable=False),
    sa.Column('visibility', sa.String(), server_default='public', nullable=False),
    sa.Column('enable_frontmatter_detection', sa.Boolean(), server_default='false', nullable=False, comment='Parse markdown frontmatter for artifact type hints'),
    sa.Column('indexing_enabled', sa.Boolean(), nullable=True, comment='Enable frontmatter indexing for search'),
    sa.Column('path_tag_config', sa.Text(), nullable=True, comment='JSON config for path-based tag extraction rules'),
    sa.Column('clone_target_json', sa.Text(), nullable=True, comment='JSON-serialized CloneTarget for rapid re-indexing'),
    sa.Column('deep_indexing_enabled', sa.Boolean(), server_default='0', nullable=False, comment='Clone entire artifact directories for enhanced search'),
    sa.Column('webhook_secret', sa.String(length=64), nullable=True, comment='Secret for GitHub webhook verification (future use)'),
    sa.Column('last_webhook_event_at', sa.DateTime(), nullable=True, comment='Timestamp of last webhook event received'),
    sa.Column('single_artifact_mode', sa.Boolean(), server_default='false', nullable=False, comment='Treat entire repository (or root_hint dir) as single artifact'),
    sa.Column('single_artifact_type', sa.String(length=20), nullable=True, comment='Artifact type when single_artifact_mode is True (skill, command, agent, mcp_server, hook)'),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scan_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('artifact_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('counts_by_type', sa.Text(), nullable=True, comment="JSON-serialized dict mapping artifact type to count (e.g., {'skill': 5, 'command': 3})"),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("scan_status IN ('pending', 'scanning', 'success', 'error')", name='check_scan_status'),
    sa.CheckConstraint("trust_level IN ('untrusted', 'basic', 'verified', 'official')", name='check_trust_level'),
    sa.CheckConstraint("visibility IN ('private', 'internal', 'public')", name='check_visibility'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_url')
    )
    op.create_table('match_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_history_artifact_query', 'match_history', ['artifact_id', 'query'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'stale', 'error')", name='check_project_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("color IS NULL OR (length(color) = 7 AND color LIKE '#%')", name='check_tag_color_format'),
    sa.CheckConstraint('length(name) > 0 AND length(name) <= 100', name='check_tag_name_length'),
    sa.CheckConstraint('length(slug) > 0 AND length(slug) <= 100', name='check_tag_slug_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_tags_name', 'tags', ['name'], unique=True)
    op.create_index('idx_tags_slug', 'tags', ['slug'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique human-readable team name'),
    sa.Column('description', sa.Text(), nullable=True, comment="Optional description of the team's purpose"),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='When False the team is dissolved but rows are retained for audit'),
    sa.Column('created_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=False, comment='UTC creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='UTC last-modified timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_teams_is_active', 'teams', ['is_active'], unique=False)
    op.create_index('idx_teams_name', 'teams', ['name'], unique=False)
    op.create_table('user_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('share_with_community', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('rated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_valid_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_ratings_artifact_id', 'user_ratings', ['artifact_id'], unique=False)
    op.create_index('idx_user_ratings_artifact_id_rated_at', 'user_ratings', ['artifact_id', 'rated_at'], unique=False)
    op.create_index(op.f('ix_user_ratings_artifact_id'), 'user_ratings', ['artifact_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='External identity provider ID (e.g. Clerk user_id); unique when set'),
    sa.Column('email', sa.String(length=320), nullable=True, comment='User email address; not enforced unique in local mode'),
    sa.Column('display_name', sa.String(length=255), nullable=True, comment='Human-readable display name shown in the UI'),
    sa.Column('role', sa.String(length=50), server_default='viewer', nullable=False, comment='System-wide role; one of UserRole enum values (viewer, team_member, team_admin, system_admin)'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='When False the account is disabled; row is retained for audit'),
    sa.Column('created_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=False, comment='UTC creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='UTC last-modified timestamp; updated by app on every write'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_external_id', 'users', ['external_id'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('definition_yaml', sa.Text(), nullable=False),
    sa.Column('definition_hash', sa.String(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('global_context_module_ids_json', sa.Text(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('error_policy_json', sa.Text(), nullable=True),
    sa.Column('hooks_json', sa.Text(), nullable=True),
    sa.Column('ui_metadata_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('deployed_version', sa.String(), nullable=True),
    sa.Column('upstream_version', sa.String(), nullable=True),
    sa.Column('is_outdated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('local_modified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('path_pattern', sa.Text(), nullable=True),
    sa.Column('auto_load', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('core_content', sa.Text(), nullable=True, comment='Platform-agnostic content before assembly. When modular_content_architecture is enabled, this stores the raw author-supplied content and `content` holds the assembled/cached output for the default target platform.'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_platforms', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.CheckConstraint("type IN ('skill', 'command', 'agent', 'mcp', 'mcp_server', 'hook', 'workflow', 'composite', 'project_config', 'spec_file', 'rule_file', 'context_file', 'progress_template')", name='check_artifact_type'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_uuid'), 'artifacts', ['uuid'], unique=True)
    op.create_table('context_modules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('selectors_json', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='5', nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_context_modules_project', 'context_modules', ['project_id'], unique=False)
    op.create_table('deployment_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('root_dir', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('artifact_path_map', sa.JSON(), nullable=True),
    sa.Column('config_filenames', sa.JSON(), nullable=True),
    sa.Column('context_prefixes', sa.JSON(), nullable=True),
    sa.Column('supported_types', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("platform IN ('claude_code', 'codex', 'gemini', 'cursor', 'remote_git', 'other')", name='ck_deployment_profiles_platform'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'profile_id', name='uq_deployment_profiles_project_profile_id')
    )
    op.create_index('idx_deployment_profiles_project_profile', 'deployment_profiles', ['project_id', 'profile_id'], unique=True)
    op.create_table('deployment_set_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('set_id', sa.String(), nullable=False),
    sa.Column('artifact_uuid', sa.String(), nullable=True, comment='Collection artifact UUID (ADR-007 stable identity)'),
    sa.Column('group_id', sa.String(), nullable=True, comment='Artifact group id'),
    sa.Column('member_set_id', sa.String(), nullable=True, comment='Nested deployment set id for hierarchical sets'),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(artifact_uuid IS NOT NULL) + (group_id IS NOT NULL) + (member_set_id IS NOT NULL) = 1', name='check_deployment_set_member_one_ref'),
    sa.CheckConstraint('position >= 0', name='check_deployment_set_member_position'),
    sa.ForeignKeyConstraint(['member_set_id'], ['deployment_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['set_id'], ['deployment_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deployment_set_members_member_set_id', 'deployment_set_members', ['member_set_id'], unique=False)
    op.create_index('idx_deployment_set_members_set_id', 'deployment_set_members', ['set_id'], unique=False)
    op.create_index('idx_deployment_set_members_set_position', 'deployment_set_members', ['set_id', 'position'], unique=False)
    op.create_table('deployment_set_tags',
    sa.Column('deployment_set_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_set_id'], ['deployment_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deployment_set_id', 'tag_id')
    )
    op.create_index('idx_deployment_set_tags_set_id', 'deployment_set_tags', ['deployment_set_id'], unique=False)
    op.create_index('idx_deployment_set_tags_tag_id', 'deployment_set_tags', ['tag_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), server_default='[]', nullable=False, comment='JSON-serialized list of group-local tags'),
    sa.Column('color', sa.String(length=32), server_default='slate', nullable=False, comment='Visual accent token for group card rendering'),
    sa.Column('icon', sa.String(length=32), server_default='layers', nullable=False, comment='Icon token for group card rendering'),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.CheckConstraint('length(name) > 0 AND length(name) <= 255', name='check_group_name_length'),
    sa.CheckConstraint('position >= 0', name='check_group_position'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'name', name='uq_group_collection_name')
    )
    op.create_index('idx_groups_collection_id', 'groups', ['collection_id'], unique=False)
    op.create_index('idx_groups_collection_position', 'groups', ['collection_id', 'position'], unique=False)
    op.create_table('marketplace_catalog_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('upstream_url', sa.String(), nullable=False),
    sa.Column('detected_version', sa.String(), nullable=True),
    sa.Column('detected_sha', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), server_default='new', nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('import_id', sa.String(), nullable=True),
    sa.Column('excluded_at', sa.DateTime(), nullable=True),
    sa.Column('excluded_reason', sa.Text(), nullable=True),
    sa.Column('path_segments', sa.Text(), nullable=True, comment='JSON array of extracted path segments with approval status'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='Artifact title from frontmatter for search display'),
    sa.Column('description', sa.Text(), nullable=True, comment='Artifact description from frontmatter for search'),
    sa.Column('search_tags', sa.Text(), nullable=True, comment='JSON array of tags from frontmatter for search filtering'),
    sa.Column('search_text', sa.Text(), nullable=True, comment='Concatenated searchable text (title + description + tags)'),
    sa.Column('deep_search_text', sa.Text(), nullable=True, comment='Full-text content from deep indexing'),
    sa.Column('deep_indexed_at', sa.DateTime(), nullable=True, comment='Timestamp of last deep indexing'),
    sa.Column('deep_index_files', sa.Text(), nullable=True, comment='JSON array of files included in deep index'),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("artifact_type IN ('skill', 'command', 'agent', 'mcp', 'mcp_server', 'hook', 'composite', 'project_config', 'spec_file', 'rule_file', 'context_file', 'progress_template')", name='check_catalog_artifact_type'),
    sa.CheckConstraint("status IN ('new', 'updated', 'removed', 'imported', 'excluded')", name='check_catalog_status'),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 100', name='check_confidence_score'),
    sa.ForeignKeyConstraint(['source_id'], ['marketplace_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), server_default='candidate', nullable=False),
    sa.Column('share_scope', sa.String(), server_default='project', nullable=False),
    sa.Column('provenance_json', sa.Text(), nullable=True),
    sa.Column('anchors_json', sa.Text(), nullable=True),
    sa.Column('git_branch', sa.String(), nullable=True),
    sa.Column('git_commit', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), server_default='manual', nullable=True),
    sa.Column('ttl_policy_json', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('access_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('deprecated_at', sa.String(), nullable=True),
    sa.CheckConstraint("share_scope IN ('private', 'project', 'global_candidate')", name='ck_memory_items_share_scope'),
    sa.CheckConstraint("status IN ('candidate', 'active', 'stable', 'deprecated')", name='ck_memory_items_status'),
    sa.CheckConstraint("type IN ('decision', 'constraint', 'gotcha', 'style_rule', 'learning')", name='ck_memory_items_type'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_memory_items_confidence'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('idx_memory_items_agent_type', 'memory_items', ['agent_type'], unique=False)
    op.create_index('idx_memory_items_created_at', 'memory_items', ['created_at'], unique=False)
    op.create_index('idx_memory_items_git_branch', 'memory_items', ['git_branch'], unique=False)
    op.create_index('idx_memory_items_git_commit', 'memory_items', ['git_commit'], unique=False)
    op.create_index('idx_memory_items_model', 'memory_items', ['model'], unique=False)
    op.create_index('idx_memory_items_project_status', 'memory_items', ['project_id', 'status'], unique=False)
    op.create_index('idx_memory_items_project_type', 'memory_items', ['project_id', 'type'], unique=False)
    op.create_index('idx_memory_items_session_id', 'memory_items', ['session_id'], unique=False)
    op.create_index('idx_memory_items_share_scope', 'memory_items', ['share_scope'], unique=False)
    op.create_index('idx_memory_items_source_type', 'memory_items', ['source_type'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False, comment='Parent team; cascade-deletes this membership when team is removed'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Member user; cascade-deletes this membership when user is removed'),
    sa.Column('role', sa.String(length=50), server_default='team_member', nullable=False, comment='Role within the team; one of team_admin, team_member'),
    sa.Column('joined_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=False, comment='UTC timestamp when the user joined the team'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_members_team_user')
    )
    op.create_index('idx_team_members_team_id', 'team_members', ['team_id'], unique=False)
    op.create_index('idx_team_members_user_id', 'team_members', ['user_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=False),
    sa.Column('workflow_version', sa.String(), nullable=False),
    sa.Column('workflow_definition_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('overrides_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_stages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('stage_id_ref', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('stage_type', sa.String(), nullable=False),
    sa.Column('depends_on_json', sa.Text(), nullable=True),
    sa.Column('roles_json', sa.Text(), nullable=True),
    sa.Column('inputs_json', sa.Text(), nullable=True),
    sa.Column('outputs_json', sa.Text(), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('error_policy_json', sa.Text(), nullable=True),
    sa.Column('handoff_json', sa.Text(), nullable=True),
    sa.Column('gate_json', sa.Text(), nullable=True),
    sa.Column('ui_metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_embeddings',
    sa.Column('artifact_uuid', sa.String(), nullable=False, comment='UUID of the artifact this embedding belongs to'),
    sa.Column('embedding', sa.LargeBinary(), nullable=False, comment='Raw float32 bytes of the embedding vector (numpy ndarray.tobytes() / frombuffer(dtype=float32))'),
    sa.Column('model_name', sa.String(), nullable=False, comment="Model that produced this embedding (e.g. 'all-MiniLM-L6-v2')"),
    sa.Column('embedding_dim', sa.Integer(), nullable=False, comment='Number of dimensions in the embedding vector (e.g. 384)'),
    sa.Column('computed_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=False, comment='Timestamp when the embedding was computed; used for TTL invalidation'),
    sa.ForeignKeyConstraint(['artifact_uuid'], ['artifacts.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_uuid')
    )
    op.create_index('idx_artifact_embeddings_model', 'artifact_embeddings', ['model_name'], unique=False)
    op.create_table('artifact_metadata',
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_table('artifact_tags',
    sa.Column('artifact_uuid', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_uuid'], ['artifacts.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_uuid', 'tag_id')
    )
    op.create_index('idx_artifact_tags_artifact_uuid', 'artifact_tags', ['artifact_uuid'], unique=False)
    op.create_index('idx_artifact_tags_created_at', 'artifact_tags', ['created_at'], unique=False)
    op.create_index('idx_artifact_tags_tag_id', 'artifact_tags', ['tag_id'], unique=False)
    op.create_table('artifact_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('parent_hash', sa.String(), nullable=True),
    sa.Column('change_origin', sa.String(), nullable=False),
    sa.Column('version_lineage', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.CheckConstraint("change_origin IN ('deployment', 'sync', 'local_modification')", name='check_artifact_versions_change_origin'),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('idx_artifact_versions_artifact_created', 'artifact_versions', ['artifact_id', 'created_at'], unique=False)
    op.create_index('idx_artifact_versions_artifact_id', 'artifact_versions', ['artifact_id'], unique=False)
    op.create_index('idx_artifact_versions_change_origin', 'artifact_versions', ['change_origin'], unique=False)
    op.create_index('idx_artifact_versions_content_hash', 'artifact_versions', ['content_hash'], unique=True)
    op.create_index('idx_artifact_versions_parent_hash', 'artifact_versions', ['parent_hash'], unique=False)
    op.create_table('collection_artifacts',
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('artifact_uuid', sa.String(), nullable=False, comment='FK to artifacts.uuid (ADR-007 stable identity) — CASCADE DELETE'),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('tools_json', sa.Text(), nullable=True),
    sa.Column('deployments_json', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('artifact_content_hash', sa.String(length=64), nullable=True, comment='SHA-256 hash of artifact file contents — distinct from context-entity content_hash'),
    sa.Column('artifact_structure_hash', sa.String(length=64), nullable=True, comment='Hash of artifact directory structure (filenames + tree shape)'),
    sa.Column('artifact_file_count', sa.Integer(), server_default='0', nullable=False, comment='Number of files in the artifact'),
    sa.Column('artifact_total_size', sa.Integer(), server_default='0', nullable=False, comment='Total byte size of all artifact files'),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('origin_source', sa.String(), nullable=True),
    sa.Column('resolved_sha', sa.String(length=64), nullable=True),
    sa.Column('resolved_version', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_uuid'], ['artifacts.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'artifact_uuid')
    )
    op.create_index('idx_collection_artifacts_added_at', 'collection_artifacts', ['added_at'], unique=False)
    op.create_index('idx_collection_artifacts_artifact_uuid', 'collection_artifacts', ['artifact_uuid'], unique=False)
    op.create_index('idx_collection_artifacts_collection_id', 'collection_artifacts', ['collection_id'], unique=False)
    op.create_table('composite_memberships',
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('composite_id', sa.String(), nullable=False),
    sa.Column('child_artifact_uuid', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), server_default='contains', nullable=False),
    sa.Column('pinned_version_hash', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('membership_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_artifact_uuid'], ['artifacts.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['composite_id'], ['composite_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'composite_id', 'child_artifact_uuid')
    )
    op.create_index('idx_composite_memberships_child_uuid', 'composite_memberships', ['child_artifact_uuid'], unique=False)
    op.create_index('idx_composite_memberships_composite_id', 'composite_memberships', ['composite_id'], unique=False)
    op.create_table('entity_category_associations',
    sa.Column('artifact_uuid', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_uuid'], ['artifacts.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['entity_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_uuid', 'category_id')
    )
    op.create_index('idx_artifact_category_assoc_artifact_uuid', 'entity_category_associations', ['artifact_uuid'], unique=False)
    op.create_index('idx_artifact_category_assoc_category_id', 'entity_category_associations', ['category_id'], unique=False)
    op.create_table('execution_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('stage_id_ref', sa.String(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('context_consumed_json', sa.Text(), nullable=True),
    sa.Column('inputs_json', sa.Text(), nullable=True),
    sa.Column('outputs_json', sa.Text(), nullable=True),
    sa.Column('logs_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_artifacts',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('artifact_uuid', sa.String(), nullable=False, comment='FK to artifacts.uuid (ADR-007 stable identity) — CASCADE DELETE'),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('position >= 0', name='check_group_artifact_position'),
    sa.ForeignKeyConstraint(['artifact_uuid'], ['artifacts.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'artifact_uuid')
    )
    op.create_index('idx_group_artifacts_added_at', 'group_artifacts', ['added_at'], unique=False)
    op.create_index('idx_group_artifacts_artifact_uuid', 'group_artifacts', ['artifact_uuid'], unique=False)
    op.create_index('idx_group_artifacts_group_id', 'group_artifacts', ['group_id'], unique=False)
    op.create_index('idx_group_artifacts_group_position', 'group_artifacts', ['group_id', 'position'], unique=False)
    op.create_table('module_memory_items',
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('memory_id', sa.String(), nullable=False),
    sa.Column('ordering', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['context_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('module_id', 'memory_id')
    )
    op.create_index('idx_module_memory_items_memory', 'module_memory_items', ['memory_id'], unique=False)
    op.create_table('project_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('default_project_config_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(name) > 0 AND length(name) <= 255', name='check_template_name_length'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_project_config_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_templates_collection_id', 'project_templates', ['collection_id'], unique=False)
    op.create_index('idx_templates_created_at', 'project_templates', ['created_at'], unique=False)
    op.create_index('idx_templates_name', 'project_templates', ['name'], unique=True)
    op.create_table('similarity_cache',
    sa.Column('source_artifact_uuid', sa.String(), nullable=False, comment="UUID of the source artifact (the 'query' side of the comparison)"),
    sa.Column('target_artifact_uuid', sa.String(), nullable=False, comment="UUID of the target artifact (the 'candidate' side of the comparison)"),
    sa.Column('composite_score', sa.Float(), nullable=False, comment='Final weighted composite similarity score in [0.0, 1.0]'),
    sa.Column('breakdown_json', sa.Text(), nullable=True, comment='JSON-encoded dict of per-dimension scores (e.g. name, tags, text)'),
    sa.Column('computed_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=False, comment='Timestamp when this score was computed; used for cache invalidation'),
    sa.ForeignKeyConstraint(['source_artifact_uuid'], ['artifacts.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_artifact_uuid'], ['artifacts.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_artifact_uuid', 'target_artifact_uuid')
    )
    op.create_index('idx_similarity_cache_source_score', 'similarity_cache', ['source_artifact_uuid', 'composite_score'], unique=False)
    op.create_table('template_entities',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('deploy_order', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), server_default='1', nullable=False),
    sa.CheckConstraint('deploy_order >= 0', name='check_deploy_order'),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['project_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'artifact_id')
    )
    op.create_index('idx_template_entities_artifact_id', 'template_entities', ['artifact_id'], unique=False)
    op.create_index('idx_template_entities_deploy_order', 'template_entities', ['template_id', 'deploy_order'], unique=False)
    op.create_index('idx_template_entities_template_id', 'template_entities', ['template_id'], unique=False)
    # ### end Alembic commands ###

    # -------------------------------------------------------------------------
    # Updated_at triggers (dialect-aware)
    # -------------------------------------------------------------------------
    for table in _TRIGGER_TABLES:
        create_updated_at_trigger(table)

    # cache_metadata uses 'key' as PK, not 'id'
    create_updated_at_trigger("cache_metadata", pk_column="key")

    # -------------------------------------------------------------------------
    # FTS5 virtual tables (SQLite only)
    # -------------------------------------------------------------------------
    if is_sqlite():
        # Catalog FTS5 (marketplace_catalog_entries search)
        op.execute("""
            CREATE VIRTUAL TABLE IF NOT EXISTS catalog_fts USING fts5(
                name UNINDEXED,
                artifact_type UNINDEXED,
                title,
                description,
                search_text,
                search_tags,
                deep_search_text,
                content='marketplace_catalog_entries',
                content_rowid='rowid',
                tokenize='porter unicode61 remove_diacritics 2'
            )
        """)

        # Artifact FTS5 (collection artifact search)
        op.execute("""
            CREATE VIRTUAL TABLE IF NOT EXISTS artifact_fts USING fts5(
                artifact_uuid UNINDEXED,
                name,
                title,
                description,
                tags,
                tokenize='porter ascii'
            )
        """)

        # Artifact FTS sync triggers
        op.execute("""
            CREATE TRIGGER IF NOT EXISTS artifact_fts_ai
            AFTER INSERT ON collection_artifacts
            BEGIN
                INSERT INTO artifact_fts(artifact_uuid, name, title, description, tags)
                SELECT
                    NEW.artifact_uuid,
                    a.name,
                    NULL,
                    a.description,
                    NEW.tags_json
                FROM artifacts a
                WHERE a.uuid = NEW.artifact_uuid;
            END
        """)

        op.execute("""
            CREATE TRIGGER IF NOT EXISTS artifact_fts_ad
            AFTER DELETE ON collection_artifacts
            BEGIN
                DELETE FROM artifact_fts
                WHERE artifact_uuid = OLD.artifact_uuid;
            END
        """)

        op.execute("""
            CREATE TRIGGER IF NOT EXISTS artifact_fts_au
            AFTER UPDATE ON collection_artifacts
            BEGIN
                DELETE FROM artifact_fts
                WHERE artifact_uuid = OLD.artifact_uuid;
                INSERT INTO artifact_fts(artifact_uuid, name, title, description, tags)
                SELECT
                    NEW.artifact_uuid,
                    a.name,
                    NULL,
                    a.description,
                    NEW.tags_json
                FROM artifacts a
                WHERE a.uuid = NEW.artifact_uuid;
            END
        """)

    # -------------------------------------------------------------------------
    # Seed data
    # -------------------------------------------------------------------------
    op.execute("""
        INSERT INTO cache_metadata (key, value, updated_at)
        VALUES ('schema_version', '2.0.0', CURRENT_TIMESTAMP)
    """)


def downgrade() -> None:
    # -------------------------------------------------------------------------
    # Drop FTS5 triggers and tables (SQLite only)
    # -------------------------------------------------------------------------
    if is_sqlite():
        op.execute("DROP TRIGGER IF EXISTS artifact_fts_au")
        op.execute("DROP TRIGGER IF EXISTS artifact_fts_ad")
        op.execute("DROP TRIGGER IF EXISTS artifact_fts_ai")
        op.execute("DROP TABLE IF EXISTS artifact_fts")
        op.execute("DROP TABLE IF EXISTS catalog_fts")

    # -------------------------------------------------------------------------
    # Drop updated_at triggers (reverse order)
    # -------------------------------------------------------------------------
    drop_updated_at_trigger("cache_metadata")
    for table in reversed(_TRIGGER_TABLES):
        drop_updated_at_trigger(table)

    # Drop all indexes using IF EXISTS to handle cases where SQLite batch
    # operations in later migrations may have already dropped some of them
    # during table rebuilds. Using raw SQL is the safe pattern for SQLite.
    _indexes_to_drop = [
        'idx_template_entities_template_id',
        'idx_template_entities_deploy_order',
        'idx_template_entities_artifact_id',
        'idx_similarity_cache_source_score',
        'idx_templates_name',
        'idx_templates_created_at',
        'idx_templates_collection_id',
        'idx_module_memory_items_memory',
        'idx_group_artifacts_group_position',
        'idx_group_artifacts_group_id',
        'idx_group_artifacts_artifact_uuid',
        'idx_group_artifacts_added_at',
        'idx_artifact_category_assoc_category_id',
        'idx_artifact_category_assoc_artifact_uuid',
        'idx_composite_memberships_composite_id',
        'idx_composite_memberships_child_uuid',
        'idx_collection_artifacts_collection_id',
        'idx_collection_artifacts_artifact_uuid',
        'idx_collection_artifacts_added_at',
        'idx_artifact_versions_parent_hash',
        'idx_artifact_versions_content_hash',
        'idx_artifact_versions_change_origin',
        'idx_artifact_versions_artifact_id',
        'idx_artifact_versions_artifact_created',
        'idx_artifact_tags_tag_id',
        'idx_artifact_tags_created_at',
        'idx_artifact_tags_artifact_uuid',
        'idx_artifact_embeddings_model',
        'idx_team_members_user_id',
        'idx_team_members_team_id',
        'idx_memory_items_source_type',
        'idx_memory_items_share_scope',
        'idx_memory_items_session_id',
        'idx_memory_items_project_type',
        'idx_memory_items_project_status',
        'idx_memory_items_model',
        'idx_memory_items_git_commit',
        'idx_memory_items_git_branch',
        'idx_memory_items_created_at',
        'idx_memory_items_agent_type',
        'idx_groups_collection_position',
        'idx_groups_collection_id',
        'idx_deployment_set_tags_tag_id',
        'idx_deployment_set_tags_set_id',
        'idx_deployment_set_members_set_position',
        'idx_deployment_set_members_set_id',
        'idx_deployment_set_members_member_set_id',
        'idx_deployment_profiles_project_profile',
        'idx_context_modules_project',
        'ix_artifacts_uuid',
        'idx_users_role',
        'idx_users_external_id',
        'idx_users_email',
        'ix_user_ratings_artifact_id',
        'idx_user_ratings_artifact_id_rated_at',
        'idx_user_ratings_artifact_id',
        'idx_teams_name',
        'idx_teams_is_active',
        'idx_tags_slug',
        'idx_tags_name',
        'idx_match_history_artifact_query',
        'idx_github_repo_cache_fetched_at',
        'ix_entity_type_configs_slug',
        'idx_entity_type_configs_sort_order',
        'idx_entity_type_configs_is_builtin',
        'ix_entity_categories_slug',
        'idx_entity_categories_sort_order',
        'idx_entity_categories_is_builtin',
        'idx_entity_categories_entity_type_platform',
        'idx_duplicate_pairs_ignored',
        'idx_duplicate_pairs_artifact2',
        'idx_duplicate_pairs_artifact1',
        'idx_deployment_sets_owner_id',
        'idx_deployment_sets_created_at',
        'idx_custom_colors_hex',
        'idx_composite_artifacts_composite_type',
        'idx_composite_artifacts_collection_id',
        'idx_community_scores_artifact_id',
        'idx_collections_type',
        'idx_collections_name',
        'idx_collections_created_by',
        'idx_collections_created_at',
    ]
    for idx in _indexes_to_drop:
        op.execute(f"DROP INDEX IF EXISTS {idx}")

    # Drop tables in reverse FK dependency order.
    # Use raw SQL DROP TABLE IF EXISTS because later enterprise migrations
    # may have already dropped some tables (e.g. users, teams, team_members)
    # during their own downgrade path.
    _tables_to_drop = [
        'template_entities',
        'similarity_cache',
        'project_templates',
        'module_memory_items',
        'group_artifacts',
        'execution_steps',
        'entity_category_associations',
        'composite_memberships',
        'collection_artifacts',
        'artifact_versions',
        'artifact_tags',
        'artifact_metadata',
        'artifact_embeddings',
        'workflow_stages',
        'workflow_executions',
        'team_members',
        'memory_items',
        'marketplace_catalog_entries',
        'groups',
        'deployment_set_tags',
        'deployment_set_members',
        'deployment_profiles',
        'context_modules',
        'artifacts',
        'workflows',
        'users',
        'user_ratings',
        'teams',
        'tags',
        'projects',
        'match_history',
        'marketplace_sources',
        'marketplace',
        'github_repo_cache',
        'entity_type_configs',
        'entity_categories',
        'duplicate_pairs',
        'deployment_sets',
        'custom_colors',
        'composite_artifacts',
        'community_scores',
        'collections',
        'cache_metadata',
    ]
    for tbl in _tables_to_drop:
        op.execute(f"DROP TABLE IF EXISTS {tbl}")
