"""Add artifact_embeddings table for vector embedding storage

Revision ID: 20260226_1200_add_artifact_embeddings
Revises: 20260226_1000_add_similarity_cache_schema
Create Date: 2026-02-26 12:00:00.000000+00:00

Background
----------
Phase 3 of the similarity scoring overhaul (SSO-3.3).  Adds a dedicated ORM-
managed table for persisting dense vector embeddings keyed by artifact UUID.

Previously, the only embedding cache in the codebase was a file-based SQLite
database at ``~/.skillmeat/embeddings.db`` maintained by
``skillmeat/core/scoring/haiku_embedder.py`` (``AnthropicEmbedder``).  That
store is keyed on text hash rather than artifact UUID and is an implementation
detail of the (currently unavailable) Anthropic embedder stub.  This ORM table
is the canonical, artifact-scoped embedding store going forward.

Changes
-------
SSO-3.3  New ``artifact_embeddings`` table

    artifact_uuid   String   PK — FK → artifacts.uuid CASCADE DELETE
    embedding       BLOB     NOT NULL — raw float32 bytes (numpy ndarray)
    model_name      String   NOT NULL — embedding model identifier
    embedding_dim   Integer  NOT NULL — vector length (e.g. 384)
    computed_at     DateTime NOT NULL — default CURRENT_TIMESTAMP

    Index: idx_artifact_embeddings_model (model_name)

Rollback
--------
Drops ``artifact_embeddings`` and its index.  Existing embedding data will be
permanently lost; it can be regenerated by re-running the scoring engine.
"""

from __future__ import annotations

import logging
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect as sa_inspect

# revision identifiers, used by Alembic.
revision: str = "20260226_1200_add_artifact_embeddings"
down_revision: Union[str, None] = "20260226_1000_add_similarity_cache_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = logging.getLogger(__name__)

_EMBEDDINGS_TABLE = "artifact_embeddings"
_EMBEDDINGS_INDEX = "idx_artifact_embeddings_model"


def upgrade() -> None:
    """Create the artifact_embeddings table (SSO-3.3).

    Uses ``op.create_table`` directly; no batch_alter_table is required here
    because this is a brand-new table rather than an ALTER of an existing one.
    The FK reference to ``artifacts.uuid`` uses CASCADE DELETE so that removing
    an artifact automatically removes its embedding row.
    """
    bind = op.get_bind()
    inspector = sa_inspect(bind)
    existing_tables = inspector.get_table_names()

    if _EMBEDDINGS_TABLE not in existing_tables:
        op.create_table(
            _EMBEDDINGS_TABLE,
            sa.Column(
                "artifact_uuid",
                sa.String(),
                sa.ForeignKey("artifacts.uuid", ondelete="CASCADE"),
                primary_key=True,
                comment="UUID of the artifact this embedding belongs to",
            ),
            sa.Column(
                "embedding",
                sa.LargeBinary(),
                nullable=False,
                comment=(
                    "Raw float32 bytes of the embedding vector "
                    "(numpy ndarray.tobytes() / frombuffer(dtype=float32))"
                ),
            ),
            sa.Column(
                "model_name",
                sa.String(),
                nullable=False,
                comment="Model that produced this embedding (e.g. 'all-MiniLM-L6-v2')",
            ),
            sa.Column(
                "embedding_dim",
                sa.Integer(),
                nullable=False,
                comment="Number of dimensions in the embedding vector (e.g. 384)",
            ),
            sa.Column(
                "computed_at",
                sa.DateTime(),
                nullable=False,
                server_default=sa.text("CURRENT_TIMESTAMP"),
                comment="Timestamp when the embedding was computed; used for TTL invalidation",
            ),
        )

        op.create_index(
            _EMBEDDINGS_INDEX,
            _EMBEDDINGS_TABLE,
            ["model_name"],
        )

        logger.info("Created %s table and %s index", _EMBEDDINGS_TABLE, _EMBEDDINGS_INDEX)
    else:
        logger.info("%s already exists — skipping creation", _EMBEDDINGS_TABLE)


def downgrade() -> None:
    """Drop the artifact_embeddings table (reverses SSO-3.3).

    Warning: all cached embedding data will be permanently lost; it can be
    regenerated by re-running the scoring engine.
    """
    bind = op.get_bind()
    inspector = sa_inspect(bind)

    if _EMBEDDINGS_TABLE in inspector.get_table_names():
        op.drop_index(_EMBEDDINGS_INDEX, table_name=_EMBEDDINGS_TABLE)
        op.drop_table(_EMBEDDINGS_TABLE)
        logger.info("Dropped %s table", _EMBEDDINGS_TABLE)
    else:
        logger.info("%s not found — skipping drop", _EMBEDDINGS_TABLE)
