"""Wrapper script generation for claudectl.

This module provides the template for the claudectl wrapper script
that is installed to ~/.local/bin/claudectl.
"""

from pathlib import Path


def get_wrapper_script() -> str:
    """Generate the claudectl wrapper script content.

    Returns:
        str: Bash script content for the wrapper
    """
    return """#!/bin/bash
# claudectl - Simplified SkillMeat facade for power users
# Generated by: skillmeat alias install
#
# This wrapper enables smart defaults mode, providing:
# - Auto-detection of project directory
# - Auto-detection of output format (table for TTY, JSON for pipe)
# - Auto-inference of artifact types from names
# - Default collection selection

# Enable smart defaults in SkillMeat
export CLAUDECTL_MODE=1

# Forward all arguments to skillmeat with smart defaults flag
exec skillmeat --smart-defaults "$@"
"""


def get_wrapper_path() -> Path:
    """Get the default installation path for the wrapper.

    Returns:
        Path: ~/.local/bin/claudectl
    """
    return Path.home() / ".local" / "bin" / "claudectl"
