# claudectl bash completion script
# Install: source this file or add to ~/.bashrc
#
# Generated by: skillmeat alias install

_claudectl_complete() {
    local cur prev words cword
    _init_completion -n : || return

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # Main commands
    local commands="quick-add deploy remove undeploy search list status show sync update diff bundle import config collection"

    # Global options
    local global_opts="--help --version --smart-defaults"

    case "$prev" in
        claudectl|skillmeat)
            # Complete command names and global options
            COMPREPLY=( $(compgen -W "$commands $global_opts" -- "$cur") )
            return 0
            ;;
        quick-add|deploy|remove|show|diff|undeploy)
            # Complete artifact names from collection
            local artifacts
            artifacts=$(claudectl list --format json 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(' '.join(a.get('name','') for a in d.get('artifacts',[])))" 2>/dev/null)
            if [[ -n "$artifacts" ]]; then
                COMPREPLY=( $(compgen -W "$artifacts" -- "$cur") )
            fi
            return 0
            ;;
        search)
            # No completion for search query
            return 0
            ;;
        config)
            # Complete config keys
            local keys="github-token active-collection default-format output-json"
            COMPREPLY=( $(compgen -W "$keys" -- "$cur") )
            return 0
            ;;
        collection)
            # Complete collection names
            local collections
            collections=$(skillmeat list --collections --format json 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(' '.join(c.get('name','') for c in d.get('collections',[])))" 2>/dev/null)
            if [[ -n "$collections" ]]; then
                COMPREPLY=( $(compgen -W "$collections" -- "$cur") )
            fi
            return 0
            ;;
        --type|-t)
            # Complete artifact types
            COMPREPLY=( $(compgen -W "skill command agent" -- "$cur") )
            return 0
            ;;
        --format)
            # Complete output formats
            COMPREPLY=( $(compgen -W "table json" -- "$cur") )
            return 0
            ;;
        --collection|-c)
            # Complete collection names (same as collection command)
            local collections
            collections=$(skillmeat list --collections --format json 2>/dev/null | python3 -c "import sys,json; print(' '.join(json.load(sys.stdin).get('collections',[])))" 2>/dev/null)
            if [[ -n "$collections" ]]; then
                COMPREPLY=( $(compgen -W "$collections" -- "$cur") )
            fi
            return 0
            ;;
        --project|-p)
            # Complete directories
            COMPREPLY=( $(compgen -d -- "$cur") )
            return 0
            ;;
    esac

    # Handle options starting with --
    if [[ "$cur" == -* ]]; then
        local opts=""
        case "${COMP_WORDS[1]}" in
            quick-add)
                opts="--type --collection --name --force --format --dangerously-skip-permissions --help"
                ;;
            deploy)
                opts="--collection --project --type --overwrite --format --help"
                ;;
            remove)
                opts="--type --collection --keep-files --force --format --help"
                ;;
            undeploy)
                opts="--project --type --force --format --help"
                ;;
            search)
                opts="--type --limit --format --help"
                ;;
            list)
                opts="--type --collection --tags --no-cache --format --help"
                ;;
            *)
                opts="--help"
                ;;
        esac
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return 0
    fi
}

# Register completion for both claudectl and skillmeat
complete -o bashdefault -o default -o nospace -F _claudectl_complete claudectl
complete -o bashdefault -o default -o nospace -F _claudectl_complete skillmeat
